author: 'lachy2901 dotblank'
database: false
description: Spout enabled NPC management system
main: com.precipicegames.betternpc.BukkitPlugin
name: BetterNPC
startup: postworld
url: https://github.com/PrecipiceGames/TutorialSign
version: '1.0'
permissions:
    npc.*:
        description: Super node for admins.
        children:
           npc.place: true
           npc.test: true
           npc.edit: true
        default: op
    npc.place:
        description: Lets you place an npc.
    npc.test:
        description: Lets you place an npc.
    npc.edit:
        description: Lets you edit an npc.
commands:
    nplace:
        permission: npc.place
        usage: /npc - places a default npc at current player location
    ntest:
        permission: npc.test
        usage: /npc - Populates the last selected npc with test code
    nedit:
        permission: npc.edit
        usage: /nedit - Populates the last selected npc with test code
    nsave:
        permission: npc.edit
        usage: /nsave - Saves all NPCs to disk        